# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160321_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfinance',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
