# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilerName', models.CharField(max_length=140)),
                ('Year', models.CharField(max_length=140)),
                ('Cycle', models.CharField(max_length=140)),
                ('DocType', models.CharField(max_length=140)),
                ('EntityName', models.CharField(max_length=140)),
                ('EntityAddressLine1', models.CharField(max_length=140)),
                ('EntityAddressLine2', models.CharField(max_length=140)),
                ('EntityCity', models.CharField(max_length=140)),
                ('EntityState', models.CharField(max_length=140)),
                ('EntityZip', models.CharField(max_length=140)),
                ('Occupation', models.CharField(max_length=140)),
                ('EmployerName', models.CharField(max_length=140)),
                ('EmployerAddressLine1', models.CharField(max_length=140)),
                ('EmployerAddressLine2', models.CharField(max_length=140)),
                ('EmployerCity', models.CharField(max_length=140)),
                ('EmployerState', models.CharField(max_length=140)),
                ('EmployerZip', models.CharField(max_length=140)),
                ('Date', models.CharField(max_length=140)),
                ('Amount', models.CharField(max_length=140)),
                ('Description', models.CharField(max_length=140)),
                ('Amended', models.CharField(max_length=140)),
                ('SubDate', models.DateField()),
                ('FiledBy', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['SubDate'],
            },
        ),
    ]
